### ISSUE TITLE
lua <-> torch dependency error

### ISSUE THREAD

**Issue by svitlanacs** [intel/torch#4]
When installing the MKL branch intel/torch implementation, I am subsequently unable to install nn lua rock:
```
luarock install nn
```

Here's the error that I get:
```
Cloning into 'nn'...
/tmp/luarocks_nn-scm-1-7871/nn/lib/THNN/generic/Abs.c: In function 'THNN_FloatAbs_updateGradInput':
/tmp/luarocks_nn-scm-1-7871/nn/lib/THNN/init.c:31:5: error: unknown type name 'ptrdiff_t'
     ptrdiff_t n1 = THTensor_(nElement)(I1);     \
     ^
/tmp/luarocks_nn-scm-1-7871/nn/lib/THNN/generic/Abs.c:20:3: note: in expansion of macro 'THNN_CHECK_NELEMENT'
   THNN_CHECK_NELEMENT(input, gradOutput);
   ^
/tmp/luarocks_nn-scm-1-7871/nn/lib/THNN/init.c:32:5: error: unknown type name 'ptrdiff_t'
     ptrdiff_t n2 = THTensor_(nElement)(I2);                                 \
     ^
```

The solution, according to [multiple sources](https://github.com/torch/nn/issues/974), and presented around the same time as code here was first pushed, is to upgrade to the latest torch, with explanation being a broken dependency between torch and this lua rock.

When is the next drop of intel/torch expected?

**Comment by mingfeima** [comment]
hi, we are trying to isolate the CPU optimizations into a standalone package, say MKLNN. Once this is done,
it will only require `luarock install mklnn` rather than install the entire repo from intel/torch. This package is still being developed and will be released with in a month or two.

**Comment by jczaja** [comment]
Any primissing progress on that one, as I also hit this problem?

**Comment by mingfeima** [comment]
@jczaja could you please try autoDownloadMKL branch
`git clone https://github.com/intel/torch.git ./torch -b autoDownloadMKL`
this issue should be fixed on this branch

**Comment by jczaja** [comment]
I'm still experiencing the issue.

I do:

    luarocks_ install nn 2>&1 | tee error.txt

and get output as in attached file
[error.txt](https://github.com/intel/torch/files/1024858/error.txt)

 git log -n 1:
commit 62b60a4da1fb3d698d79852f23530d38d7d46a51
Author: Xiaohui Zhao <xiaohui.zhao@intel.com>
Date:   Fri Apr 28 01:45:54 2017 +0800

    fix for build error: static declaration of \u2018luaL_setfuncs\u2019 follows non-static declaration

Please advice,

**Comment by xhzhao** [comment]
@jczaja hi jczaja, you will get the optimized nn module installed after intelTorch installation, and you don't need to "luarocks install nn" again. Why do you want to update this nn module again? and for now this update is not support yet. 
We will release  standalone packages which totally fixed this issue.

**Comment by jczaja** [comment]
@xhzhao hi , I'm novice in torch, so I may not use it properly, so perhaps you can advice me.
I have intel/torch installed next to original torch. I use openface project that is using torch. It works with original torch for me and does not with intel/torch.  Instruction of openface project was to use luarocks install nn . If I skip that then I have an error like attached:
[error2.txt](https://github.com/intel/torch/files/1025054/error2.txt)

I would be gratefull if you can advise me on that issue

**Comment by xhzhao** [comment]
@jczaja hi, i build a temp temporal torch with our newly developed modules: mklnn and mlktorch, the link is https://github.com/xhzhao/distro. FYI, the performance in this branch did not reach our target yet.
To use this repo, please follow this [readme](https://github.com/xhzhao/mklnn)

**Comment by jczaja** [comment]
@xhzhao Thanks very much, will take a look on that one.

**Comment by xhzhao** [comment]
@jczaja This error is fixed by recently code upgrade, please give it a try.

**Comment by jczaja** [comment]
@xhzhao It works now. Thanks!
